apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-storage
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
