apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-local-pv
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/zfs-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - talos-npz-5d8
