apiVersion: ENC[AES256_GCM,data:5ac=,iv:0wBbG1VaSLyh/uaIP4FCM3e1CGRRvhaQpb+w7L6VBrU=,tag:zQeV5W3ifwZjwghgM8MvQg==,type:str]
kind: ENC[AES256_GCM,data:d5HfD7fi,iv:yaqOqRtJsNYOe65lzU6ig2Y2lmjOvfAsX+bsBbcon8U=,tag:kwIlc7BBRmvY/GfL7IBlPQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DSPyI+mzDfvfv9VdGL35UvZuR08=,iv:KA2zGufyIjtX7QNL+nXE5ef3NpBhMPHcfYppJJ/P/b8=,tag:uFu9QWuO7sQwCLDPadkzaA==,type:str]
    namespace: ENC[AES256_GCM,data:yKjTdFrVhQ==,iv:fbfYeFhD0M0snmU7MO3uNR1vd5DNI82zLyJjVIYeb94=,tag:4S1Jyke5EQYfPFWgqgxB2A==,type:str]
type: ENC[AES256_GCM,data:gHUkoeWt,iv:xRdw7gWNFzTXG1FAOfn2R4lK9DJJG2GXETUf23yMM5w=,tag:0bWgNdtubnZMD2kFllkV3w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:gu+Ycg==,iv:KnBCXTfm+4uzUNASofN1y5JvRN48aXTU6zeNPoTw5gs=,tag:wDr1ggV6mcmZUnDjC3QcuA==,type:str]
    password: ENC[AES256_GCM,data:UQb5WC9ilj9vWHq/x8z2iPKm7r0whZXA+FZPs8Y=,iv:1ytxJHTh6kBeUq5/6EAv9geOWtzpZ2uPCa4fyJ8Gj3o=,tag:hSWpGDOsEdHC72qxcOXVFA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-21T00:49:10Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAHj57MbKa5vt6DdiP19vfYbAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZ9JqzifMxg6QiK4kAgEQgDsxix+k445WZTcOlNgnaS3yuzhaSOnh/ORBHI6uLtp3mtkYlBOWmTGXMjQT2K2hu/MI+5ZpRZSSF2YBmw==
    lastmodified: "2026-05-21T00:49:10Z"
    mac: ENC[AES256_GCM,data:dVdZ1FxtHWLc8wNVpaID0rhvN7D2WUOnKr03mAuExNL9cmEDGGCFp3mOR9qR6Vlomjj4y1Tk4P4AODzKY52j7LxJVUTCKzAQHdxvaGKjFlnv9RpL4G7kbZaqoG+JxCwXTxTpSjO8rm9J0EHCq1pf0lRLSTgW9hnh56JRFOipyyo=,iv:dP9sJjwyu6TnBkQO0lBPfUJb0ruqhXLFGate1wUpYFg=,tag:AWcaqNwIDw2gyAWbgTJzrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
