apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  labels:
    app.kubernetes.io/name: nfs-provisioner
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
      chart: nfs-server-provisioner
      targetRevision: 1.8.0
      helm:
        valueFiles:
          - $values/infrastructure/nfs-provisioner/values.yaml
    - repoURL: git@github.com:khanhcmlab/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:khanhcmlab/gitops.git
      targetRevision: HEAD
      path: infrastructure/nfs-provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

