apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "forgejo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
