apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-dir-creator
  namespace: monitoring
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: grafana-dir-creator
spec:
  template:
    metadata:
      labels:
        app: grafana-dir-creator
    spec:
      nodeName: talos-npz-5d8
      restartPolicy: OnFailure
      containers:
        - name: creator
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /var/mnt/zfs-data/grafana
              chown -R 472:472 /var/mnt/zfs-data/grafana
              chmod 775 /var/mnt/zfs-data/grafana
              echo "Directory /var/mnt/zfs-data/grafana created and ownership set to 472:472."
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-mount
              mountPath: /var/mnt/zfs-data
      volumes:
        - name: host-mount
          hostPath:
            path: /var/mnt/zfs-data
            type: Directory
