apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rwx
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
