apiVersion: ENC[AES256_GCM,data:RDo=,iv:6/sx05h8zN+EqBxS80/5007IzwoCLZISHK6UMkFCtnI=,tag:TeInuGmMajMTu4EjOHS0cQ==,type:str]
kind: ENC[AES256_GCM,data:Ta/8FIYU,iv:ltQmZeqlQA1mVu02/7WqlbKLiaFibIHuZcRN8fDlpGQ=,tag:4mB31whXmLEPopVBkfMIPw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:Xeyxz1ZFZQBldpJfCi/r71q4KSg=,iv:T4LZ8zhcSENsnV05YHsB4+ohJwgMxAR3wZOXbYXj9Dg=,tag:fNL0KCZ2W3E/d0m0GOTeyw==,type:str]
  namespace: ENC[AES256_GCM,data:uCOQdk8xqvsHnA==,iv:q6iqJ/TPNvGPYCn3RoHWMroCEMttsbg2gEGKWcWZuHI=,tag:lN6rUbI14f0m49BMqgtqsA==,type:str]
type: ENC[AES256_GCM,data:meYIkkUm,iv:8rVDnKqv85q7tX4tphRYekOCzmFPyaj1fAMcfGMgwVA=,tag:sa+sYmnTeZeYJuGnHAjDpQ==,type:str]
stringData:
  admin-user: ENC[AES256_GCM,data:W9rO7Go=,iv:samcDSj0SNUXeiKNEp/GUNT6qq8Tsx2rO3QBajhFxBs=,tag:6Vvn31CMz/+/6wS593ssVA==,type:str]
  admin-password: ENC[AES256_GCM,data:0ok2ALmjYQ7iCnYN34pUMSNNynoFLP5lZL/P+xrU/onE,iv:dvPqYlyuQoK//8ifKd8WghhUQdWJwM/uohR1Cny15x0=,tag:jp6WCSLlWf1Ww0txT7q/pg==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
      aws_profile: ""
      created_at: "2026-06-07T05:46:21Z"
      enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAH2Q2LPOF2TS0Zayt1lTyq6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnPLOrLwdF1s5MAWUAgEQgDsiwwPPm88JEoWrTqur6BiOhyJgUvLOLecV5GjTdJHtAOcmv65Hgn9hSdc9bHOs2LYEi10ojM5AlZUKtQ==
  lastmodified: "2026-06-07T05:46:22Z"
  mac: ENC[AES256_GCM,data:tvxXV15aOxPERgKrdNPlqIwUVRMWAqwH0EWqZOBBdoxD2vLi2g4R884Ci5r1B6BPYThMGTOxNFQ60QNT7LNK82DPMY+pVlTymEYKPIskF+8295PaMoszl+eKOQRXVtDmArrUKPLK9fuAVaYxXRAwvnT3jfAcaqNqWd+NOMaBOGI=,iv:uXxsZ8m3YvjSAl6fjWRDChAebPpOhj5jTeAFdJIGzTo=,tag:DF9z89hKF2dqoM+mg2AZ6A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
