# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: longhorn
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: longhorn
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   sources:
#     - repoURL: https://charts.longhorn.io
#       chart: longhorn
#       targetRevision: 1.11.2
#       helm:
#         valueFiles:
#           - $values/infrastructure/longhorn/values.yaml
#     - repoURL: git@github.com:khanhcmlab/gitops.git
#       targetRevision: HEAD
#       ref: values
#     - repoURL: git@github.com:khanhcmlab/gitops.git
#       targetRevision: HEAD
#       path: infrastructure/longhorn
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: longhorn-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
