apiVersion: v1
kind: Secret
metadata:
    name: openclaw-env-secret
    namespace: openclaw
type: Opaque
stringData:
    ANTHROPIC_API_KEY: placeholder-please-update
    OPENCLAW_GATEWAY_TOKEN: pp_iPrcfunnimwdubbE-PFovghqGvmnulaAD@EjsD6swiP6GTjf!PNX+YuOMet=o