apiVersion: ENC[AES256_GCM,data:Apw=,iv:Ys5LqzcnD5YCCXA0kGFv1+cGFCdpVquUXsPIbwDTV8M=,tag:5DiCqffHbxRZfJgvHhlgog==,type:str]
kind: ENC[AES256_GCM,data:KinaaUn0,iv:oMb2DbdaYkm1pXr5d9VNKkmmACkxwKaeYTVWnUs5l6Y=,tag:kbM0XI+Zrt491ze7icH6lw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wfjo5ApOd5LXgh0R5HnmCADIdw==,iv:nrSenhyyeK3Xr/XvXiNjdu8udlP+dcvZHWFyQ85sW1k=,tag:8IITHj+Yz5j6c8/eT6kqPg==,type:str]
    namespace: ENC[AES256_GCM,data:JMdMGzw3Mf0=,iv:dk4NDwLiVSyfVsCBnyDwVRwbC8Sum/OAB1cJmA+XFs4=,tag:gT9nmzCEtOSfko4Tc7qWkA==,type:str]
type: ENC[AES256_GCM,data:Z20On7jb,iv:U+WiR2Uld307N8Ar632mAyGi99KnWL1x7bQW/WZbY/w=,tag:MfSm/1vjAjKXfjlba1/uTg==,type:str]
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:ZCNH1ew8xOgnUEacqplOQtGFyjCYH+V57g==,iv:4FyqGwjJBu7JxD6BcPVModd6NfsLdDhqQ49XrtzkXIM=,tag:+mNfFLmxrl09++akArg3vA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-26T15:03:51Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAHjkMrRUZJJdRwN2NhsBsFPAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM19ZJiGIanNCp3mHTAgEQgDuifHXTmVqapGNLGE1gzcwkvGfrqD4Is5JT0V1TVhEafJDOCS34I7w8fZWIzyqQmBW8PqFsPJzb6W81vA==
    lastmodified: "2026-05-26T15:03:52Z"
    mac: ENC[AES256_GCM,data:1DNpXXnVmR3uit6jSAf0ouu4rjq5soJZyaEhLmPwY7cY9CAGQpSWyutCMXHCwWnw4GGh4knWeqG/YSGYNaUGennYNZNNU6HnzktN1M2pD3iw7sWcOpQtq03b1GyS92249vTBaqIO9qjyBPUjSod1y0mtcH3KPkcgKJo/jB0vRzU=,iv:XAZDlYNWiKn7OW9LUZJ9r1f22IICOWFE5WyNk3/8/R8=,tag:tOkBAusGsfwa69zAUPW6+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
