image:
  tag: "2026.5.22"

persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-storage

credentials:
  existingSecret: openclaw-env-secret

openclaw:
  allowedOrigins:
    - "https://openclaw.org"
    - "http://localhost:5173"
    - "https://clawless.khanhcm.site"
    - "wss://clawless.khanhcm.site"
