app-template:
  openclawVersion: "2026.5.22"
  chromiumVersion: "148.0.7778.97"
  configMode: merge
  skills:
    - weather
    - gog

  controllers:
    main:
      containers:
        main:
          envFrom:
            - secretRef:
                name: openclaw-env-secret

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
