nodePathMap:
  - node: talos-npz-5d8
    paths:
      - /var/mnt/zfs-data/local-path-provisioner
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths: []

storageClass:
  create: true
  name: local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
