apiVersion: v1
kind: Service
metadata:
  name: tekton-operator
  namespace: default
  labels:
    app.kubernetes.io/name: tekton-operator
    app.kubernetes.io/component: externalname-service
spec:
  type: ExternalName
  externalName: tekton-operator.tekton-operator.svc.cluster.local
  ports:
    - name: http-metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-operator-webhook
  namespace: default
  labels:
    app.kubernetes.io/name: tekton-operator-webhook
    app.kubernetes.io/component: externalname-service
spec:
  type: ExternalName
  externalName: tekton-operator-webhook.tekton-operator.svc.cluster.local
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
      protocol: TCP
