apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  labels:
    app.kubernetes.io/name: cnpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.28.2
      helm:
        valueFiles:
          - $values/infrastructure/cnpg/values.yaml
    - repoURL: git@github.com:khanhcmlab/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:khanhcmlab/gitops.git
      targetRevision: HEAD
      path: infrastructure/cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true