apiVersion: v1
kind: PersistentVolume
metadata:
  name: zfs-local-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/zfs-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
          operator: In
          values:
          - gl