apiVersion: ENC[AES256_GCM,data:KPw=,iv:fXsJqARk1vq1LZlqGaMIryfG0rvqd7g0P5/V1PWxSOY=,tag:7DqInhoIKKEq/wVGdh9VIw==,type:str]
data:
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:yQwY9F4dy0j6XlKOvZHV1+F4AiVwPKnpFv5Aiz+dxl7sn0IzgdcqMg==,iv:EfK/uiLjdVeqC+ATrXa74IbX44a4aMFL3Nuukdl2nEA=,tag:hHiF+EeHW7byKFfGtygY2A==,type:str]
kind: ENC[AES256_GCM,data:KJFPgfmB,iv:YA17ALgrzEZd+vO3/EbqsyO0DTuiyEciCIk5SB8QkT8=,tag:JmU1FjumAk4wlPkQbAJoOQ==,type:str]
metadata:
    annotations:
        argocd.argoproj.io/tracking-id: ENC[AES256_GCM,data:9us8qVq+xkSkyFdfDMq8OT69wsEKLIGFDmZK4w1DUllENiPQo70AZ2PG9s0=,iv:BKGAHm3lWmxKMx7SoAS7MroFXzmGHXOQIW/6lqWyo1M=,tag:ZgD6We4ryCXhbFI6Yfj5Aw==,type:str]
    creationTimestamp: ENC[AES256_GCM,data:lY4QrSWREk4RCRkrzT53AnCeVuA=,iv:1+H1AxYrgIYFYy/7vJ31Ib5+0iwSZJtWc+aP+OBWxwA=,tag:t9kZP875SD3Wl790vUcumA==,type:str]
    name: ENC[AES256_GCM,data:OtvZNTz3bToVBrZrqldKCwc=,iv:pq2DopW8TorodpvFTVw20vEWXbgtNUOg+f85hCQFTb8=,tag:wfbuPmaN0gYkHazf6eGaDg==,type:str]
    namespace: ENC[AES256_GCM,data:1E1e8DWGUs5uCgdxN48=,iv:fez8IREg9PhrRnCZ9V4mSZES7WGL6ZI9SJafQ6Mq/Zo=,tag:tK2CLtIVXYLr8FPiA5oC1A==,type:str]
    resourceVersion: ENC[AES256_GCM,data:xDWmcV8Z,iv:Ux0eQoEykz/8AHrJSWUzVI3xE52NR8AOTHRNsop4UCY=,tag:bS8R9iqUq2WR8KYOktUZtQ==,type:str]
    uid: ENC[AES256_GCM,data:6NcPXMi0lmijwA4bmOq5+1HCfCM7guzvyQs3+0pY7eD+shDL,iv:P9DECiB/x+ND/xttUBAk9ZaWdanIYGxh45PSCBatUJ0=,tag:H3F3OcCiMrSv56UR/KwvDQ==,type:str]
type: ENC[AES256_GCM,data:Bw+bAokx,iv:02BsSJc33IPpDRwjqDtAgU54Y3mclk6+zR9sVWRCCgg=,tag:hHcWJZmS+yd3AEAlduUCXw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-19T15:16:56Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAH88+FU0PmXYATSyZds8sR9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9e/iwAT1CrbNUlRwAgEQgDu9uG2Z849ckdE6ITcm68fRThKW5Ce+FX9rky9Y4a6czi5EFxlqfDUY3OzWbqwYRrcC3/GUlm/MQ1qv6Q==
    lastmodified: "2026-05-19T15:16:57Z"
    mac: ENC[AES256_GCM,data:v0fxOO1lYBfAJc0ddNIrJ7JTrzoDCffoiHg0SfFG8YtUQfDG7YZjJJ5ZBP55qgHTFXfRZe6KAPB4IEtMMDjBrMT8nQOXh8ZiV40n3UmHmT71zJpk17s2Ly5n9u6yFDx1zepZ02p/vSPOkfPhektQo9dn63t8uuIOG4erkUK0CVg=,iv:PAO6ZM3wLo5K16NovtgsFS0V52T6RghhRraauNtvL28=,tag:aPnlktqbjbQ41hyWupZfLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
