apiVersion: ENC[AES256_GCM,data:TcM=,iv:BeFY7dQwhTsQfwAh9U6j6YgGx3BJzUbGPGykNQEdSeY=,tag:xDzRgeDK+kX97dUbS8r0Vw==,type:str]
data:
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:8sUhsFlXelcuO2hde6BGmj4R8wwm9SQURlHPPEiUED9OY/0lTGzOPw==,iv:2t470uLzv+WhKp3u2aUKTqHPMUNY1PZaq+pFcZMz6Yk=,tag:veBY3I4vu+Yk93Bkisz3ug==,type:str]
kind: ENC[AES256_GCM,data:5Jaub+RQ,iv:7UozwQ4ip89XxZUdfng55S7a35O7d8tj1bjSBX9vs6E=,tag:1i/ii8YFftAAV/Mx/kBM3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i53z7D3op2L4MBmCh46SXBI=,iv:0uPHbY4H8RQZWBzBT6NBLJUiqQBpUgYi/Ki6+0VbB0k=,tag:P/V6hsDH6CMXpYohsuxSmw==,type:str]
    namespace: ENC[AES256_GCM,data:i+R3I3dXRtz/+hskquw=,iv:MdbjIeOzDEY8qjE1IdAkBMh2GufDatcluvLeaKCcnxA=,tag:TQxNcnGaQ4T9UOzLkmUkkg==,type:str]
type: ENC[AES256_GCM,data:hV9ULxyD,iv:84nLegShE+3jaNA77lPCnUIdevX2DUROhGMCqRL8teM=,tag:8McEJUXv3+4od+rpTissMw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-19T15:26:49Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAGiuVVs4IMan43puHBSjarjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTfKUj97Sxzdrj6L9AgEQgDt1H6kpo1wYCp8v4i7knAvY3DrY/4rJAVnsOtAzDcPOf9lct2KLElwTlOVP40Fr2gTQHMUfzEPjqMCvVw==
    lastmodified: "2026-05-19T15:26:50Z"
    mac: ENC[AES256_GCM,data:EKBA96d4YlUEOC9YciwWkd0P5idoaSb/14173JwOInkA/ZDwgc7iEv63QufFEC49J/2grNTw0lpT63HkfOHkac3BP6peVVZmVSQLKTj5I89YiVl+XoMzEswHJC5J1xVhk851GlMvO/Wqzu82hEBndkpTCmuehsHABwA0KlMfKJs=,iv:OlCq/I9DKZAWy0AdOfOCYMxUux6gqr3Qc8RYnuS0KOI=,tag:+lA86z+d+jVWNT95Q6Abbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
