apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: argocd
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/component: externalname-service
spec:
  type: ExternalName
  externalName: dex.default.svc.cluster.local