---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: dex-argocd-client
  namespace: authentication
spec:
  encryptedData:
    ARGOCD_CLIENT_SECRET: AgCW8rj5Bou2otnucdHH7T44yBcKQGd2016GKyDnJfSM2EPIJ3jRRNqDL+lfhScwXE8/G3qiWz6QRstybl2XSaV0GIMYJm3Wer/+KPprmDkxM5YWooWIrTWG1yw1lHpySf5lmBvOxxmRZOx6yuq05llMIz8ZWqE+c1+pPwhj1tH8r+oP6N3DKbf1cLRuCPCsTo7dgkqT9GIE/9wZ0+BrA3XvyEv/7f4VG45ijDMTXJ5G/0d6vwTsBAlwDN4rnEaPDCYTR+BF4005FvOjK6s1YdrrGZAk/YXiBxCrAWxUe82esmeyVicSbwqJPkd1SV7mL9mWohboU7WuefDuDORMWbPRsPPoHOLJgObNn+23iDyAwEnIdXyTupKNkoADomF1P/onFIiwAkyJeSPRH0BjDfpSzWWiTKfLmlfLrpwt2H+x6pB1OrnpNVRnRG/ADhgcQ8glnmzonfyBdWnnG/VlWpVPXh/1uCHxMywEPS9FTxv+ybKmauy6wqbBElc3Prrkr056cmjLb0QiwBTjWhozyszBX+gknWtW9sKqVGpbBEYd3hiIvUAlV/jZTIsCtTODLMEfzsoqb5QdCg/QliDEZvrHspsuggv/1fj2hdRS5MZ+Sn61aYBH+YjVMdITz37ffo71rJlm3/7zigmCtaSl0H379vhWM9WsW3VzIZGo5TUVH+iOKzw9M4GNPZjUbd83lTCIqVuA7nydt1EVFzHR0mMGuw8w25QrdzOK+gi1JirfG563WNHuCm976ake7w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: dex-argocd-client
      namespace: authentication
    type: Opaque
