---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: dex-github-oauth
  namespace: authentication
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgCG3crCd6L9jD3YbBwfOtMiHbtjg8D9bp+ZjeTv7kydhdvi+s8JaLlo6ESPMVOkRsNU8woSET5LGhWnBEGqV3vOTt0t4+p0L9jKpY+QvS02fnU3mT5Liue9/IYlLjDGYt//+8P1Ebs/Nsf5ATxpk1CARBbnYuF9aTOObkK4hivlbfoN9wwKR/dOzdO+U18DMAjmA4hwmNLL4311QYtnyk7MnZnsOc6z+rqgvwhNxTHyPXzBGaiPaJ4iJNLEwHmYpL5P5u3zOLszDH9iO/KkUI+vupnUlrhbeDML0Q4sC+tCKRDw8qe5sVmWJwurVQqR6UecRQWXUvWxnySOiZYJFLBIEF6Gk4Kc19DzpP/VkrTaJr5IHXefTXgq8tP9XSi0EkshlSVLTh5BlR5KlsTgV7Pxt2SvD8uunn7k5+aXw/QpIfgh17cNo9+QADRGWDgZZjIZWKaMRLzJxSf0qYQUl55tySj4SZrQr3jtcVswedtSmses0ysPQgAp6MdWXEDFwL7Q57Y/b3FITmX738A0hli8iZrzHZ9YhlMBRQE18rY+esnz1OwLyYYQRGKzf9gY54eJhJVtYKz57eKk8ttEH0uoiV5wHWSecuLHDkRbHFbpSTxmopc/USvHY3Q4K652Jk2C0xkvb1ap4I8Mx9ierFBlO5ymmsupG4a3wPzpV+mNpRyKIQmxgK3hlFnO2meHxZRcqOEDJDsP
    GITHUB_CLIENT_SECRET: AgBm6W+bRqOvaG/aeBfyam1k0kIsOh/eaKLfFSFISWx87Ohy+hKARugtZwFeWQkO+fPoO3LAVIJoUKYmRm68qV2eT9v59BJ2wL6HliiMkHSoajNNLELyTn2jJDdlJcdvPLeNyMUC24ES6njCQ1VeRP5h/XHZJCDaO34k9Qor+HV/QcrOR+wAFyOR+J45v9VjH3WiLpWOL2Nf9PPKk3I1XVslATvMvnAaqJpxP8la6DpknjPvQovUTtVNOflvPeO0kvF4xRvhhDtW3++Pifh1CfD+Dni3+I85pvc4KBRLEOtdCZ0Y+4SeifMWbeX+ikbdB2KPmUfioH1vZDpYtSsj1zD5JWbCrjxMf7GTgfakFSA8AZIMUW8EdkQ+jmNezwGV71YdLNnAEvkg5hmajSRnAnN8toc0BwBgKHN5jSQZwqbS5iGIX/QOLF4m/XjpCRCerctVAjLBi4pDMC9o1P+SlxWYmtoYsIQkbOjFLsou9M980/j8shp1TJM2uBAXqe6A7ZhxCPmHfj2wQxlaUr5BSj3SM4WziWg48EOkD+Alrd/plkoj/rgdw87OYRlqiDt84Y56O3i3q1NAQpBbd9OfdAuD4yUrTAko/Xp5Wf5+gaf7xOBcbho32uwR3eF6eseCkLr25Ix7EZR5bx9TrgRC1mmAtUf38uTmnPwO0x9f+jnc/mvLVV/qRY6Y7GajxzQ00mdxnQ54FvUf/Tl/Fhb89vU9hZkEkvEj73XOV/V34MjlcssYqNc3YEmM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: dex-github-oauth
      namespace: authentication
    type: Opaque
