---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dex-github-oauth
  namespace: default
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAXjDgHpAkOOHf75IalvViiAdNet/HhfW9ptviIONyt26B0qPiGI960gR/hTfXgDYyz0uPz/I82/vhGy1MVw3ogGwo1vg4G3qdGrhMRQePT62ir2JKJra54PKjoqTXUvWb7rHRE+0XO5qShzz2jwZKwLAu07/LCei2CRCt87YHwXcmzABVcGMOvXHDwb5HbARvkW6fel3KWfkJz8mWJcxdh90QESysDd5mm5uMEmQ28vXGyF2Z66FKAD01B/dfGtOFTEovsV6UDzEevSq5noR9CA0Pdw/4mFt7fSs96dXnGgUJli5P3BcsQeZplSH9h+oabPmnqI1ZCLDK5Ibvf+jseMCbgW5i3Zq3cC4Lc0iS+oA1XRLbuTOpZaCwGA4kNgXnIJoxF6I1iRDfm41oQ6axWaGY8NHk2wmoqmdRO8SFojn7LPKXB5NcSLh5jgwfFSQZNzDC064men2aS+pX2b51wvQ+mi144SKNuss6qz/sznRz156hVOI4d1SxrcInwxvdcm2G4ASqzA1tw0lg8Hkh1cH6j0IOEtB0NoCNr64ic5XS1VVJAiqHTR6fA98Mex8ZUdZQBikSZ7OsRsVLOux3XEKLlhI6wsyLJX/srrxzlrT4RofMBxBKuKDs93j2SvHNNaqlFzj8l/n+cpVYMX2y62m6Kagiq7Vg0fm79NI55yGM/diVZQewsXgubIJ386a1yO9Yb93KM
    GITHUB_CLIENT_SECRET: AgBvyyq8wQwTLb7Xq4fIj1SAbH9Eow/V2PThT9bxQE4pmn+vYTktVTDWU6J6E1B+cxiBJ13D5Fgvm1soj8x0EkFzZWeJQn0ejsx+4liwNNKDhf/LqPveiWSW155jhDiR9aQR335P4VFue36Xb3QL0jgI7mdkC/Qr21Q8LAJ1aS1mVXfyhh/iBWgxXgZFvCGjz/LR6wjGoyAsAqAy+PNZMV8nuXaZ8gfUuHEfgDpoOxg6mBMaein6qLKFwyQTVlDe5JZeuQHyekhPGmP44/TVKdrHJu076H2QMDg3d0EvCnZOLPh+LqFaIvHVlG+4ElEinEg4ybEnIT3Ty1GbPfZbi26MUJQsrwpoD1chbEL3bS2bnCayI/jes/r1d73SbNIqbkuAEupFdtpQENrezbC7kzu5jWOZ5tZ4HpFWawTxDmMEvsSTeA6yzNt/ODktDi7i2f7hBRlEZyqHWoHGj/Oko8wsBBPM+jIPAB5x6vUDiLhX7IwgTrq5PSwjQxR5ZuhkIt/UnGax3v1HXmL+738TOiufvU1D1houtefuaaKQqIE201vJE5/8kLxbBv8tYu3R05ZcGjwMp5LfUCizefHTtkQjqhcCk9QwWbi8DKvCfKZeY6QEV03P2iEg+oXPBrFVu1ozoh3RcWYuVOSkUTx0bJR+GnnLi0aVuLfMAt9T82Yxmc9oOXtw3MO3RuUFdjLeMN2ToU/eeDocnPmvQcAk6924U/Ewl6PQgtOjNRKXheiS18hMlHZUzeRH
  template:
    metadata:
      name: dex-github-oauth
      namespace: default
    type: Opaque
