---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dex-argocd-client
  namespace: default
spec:
  encryptedData:
    ARGOCD_CLIENT_SECRET: AgAdHCL8XNPJQ7CE+eqZeou0ErUhiW6iYoUAbxqGoTDSuMhfv1cE7JzwZ2+4JzuYUhy50CFNS1A0mvh2anJJo4SjSQ9/RLUhuQ03GlwH14oQJQcs1txnRbf43lZ9QcxcOU1HjbIhU3QbxLJAx0XatN3dqjSz1hnrQ522sW0yBVXZJNP7U6jINxSq/wVmOawzIIWemTC6+ULA4lgfPPGQVIgF6idOm6Qtwt8rfvAWJwNV52nrt6cv39KBmni24ztgAVQLHvKPOR8+ejJXMdh1nJQCur0AvOUexhLwD1xmqViOzx6Yj1dTEjOEtJvp5ZhWeBFAfe1lTGrMeW45dT0Em8GSG/p4/LM1Ct7XWvy1eOkh50GoRmYcs2lCoJaO/MA+2ayR7phvMn8pvAs9ZSxdkY0mLnVPtptp8v4x6lRiol/r84WOhaOXL8IIG9oOTpafGmJJ4jCATZEAD9fBGHKXILRP6y06cIkbd8BkMgTQfzNG6vbKqUdCo5+pzBhZ0T3+2hQQXiltOiTSk0/JSsxLyYtFaYNh+dU3rT9AnS+Af4O1/U/xQb5uevGitQl73TwadsBlwRKWbfiVB9fVIXjA/O+g0G4dEx7Tv0BBaW+ZnI2NjisvWFkRwVoY2Bv1mmJxBadR2XQbzfjnuuqLeZTy+YiDGcYNaLD7fJwCwKTkRC54O37Aqp3+0f7Kkp7E1APB2BFhTOFqys6j9DxMZdvCSO/Cvg4l9OIvC8uxVVSNsAkeyFytyRAcZuJLC57rTQ==
  template:
    metadata:
      name: dex-argocd-client
      namespace: default
    type: Opaque
