apiVersion: ENC[AES256_GCM,data:OLA=,iv:KFZhabcFMEaYYMBKoifgepcpXpEncAQ/C9og2jAZ9xU=,tag:v5t0r1r+G+eAGv5LhsfiHA==,type:str]
data:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:3ZwgwP+5TAYSFweoLoAWp7SxSZBVYSirgWyUrQ==,iv:FsyQjbvV73Y04SGxOUsQz4VfduLLAlyWkq4T8Groz6g=,tag:tINPQxYngc1Yi4cvZIxtiA==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:JJMg+8uMnxAveSb7KR581yUuz21DRkzOdzw0Ro2nZI+stO5Eak6ORnGJAaHlBFnkJiY8F0swWiA=,iv:GUrLRhOcXjUkPXanGfE3xtnHdjuP2jogDy0bt+UWBzs=,tag:blIFLhFPi8NNKMYJalY8rA==,type:str]
kind: ENC[AES256_GCM,data:G+6NXtaM,iv:Bqt1UKJTn8RjsYGXH4DN0Jc0VAeElEsKxhNikGGDuL8=,tag:v2hNu9P4yfsE80NWmgrmVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3dx0hssECEdDg8GSSFjSnA==,iv:w+cSA9n7tR88QrZapF7XNujo0WdWrz3B58AlY1w1nws=,tag:tm2CJ3HL0KNxaxdwZUYcPQ==,type:str]
    namespace: ENC[AES256_GCM,data:29wS5NX61cSn/X4Ssig=,iv:XBQN51Wts3fLlIkVh1TCC3X523jx4XUNbmPsQ9JUhXI=,tag:gCODslUNfecNyohVJa/ABw==,type:str]
type: ENC[AES256_GCM,data:w2P/37vn,iv:WMdkZ/SBgmVrjqpjfUgQ+L9qePAVHxSMloPJ1kObYVs=,tag:8IaQCFVd8ygI2zdMIir3vA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-19T13:57:57Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAEN8ExZBYZsD1HpTE5cwE3pAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMp8+iZ9rpJJfwebQMAgEQgDtWW1J+gEKoEODXlS1hjQuVZymBOSLmr/7xazthxEW6HpsLE3NWm0IC4KEKHha7JTUAWMtqLmtd4VwpjA==
    lastmodified: "2026-05-19T13:57:58Z"
    mac: ENC[AES256_GCM,data:pMFWHKc4cnH4DMUWkfuG5/RIEheU81EDhqF932Pgu2PrR3zxpXgdTsyZfCbcX2Q49npQdm3h23jfk+CyMcixAHY08nt5djjnZNpJQMMi+MUfB/jlepjByLlqsFfcJszei1c4AetZqbt7Vf5i2Tw/LTbdkeG3N0hCukTRzfQsdyg=,iv:4f1od+ZfNETgg04/YdEcbZnIcNNctt1K+DPXmDC5ksU=,tag:ExTaxVC3mZD0l5SXG5/23A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
