apiVersion: ENC[AES256_GCM,data:mww=,iv:SHajad6tX+nAML6NLPBfNVe/eiDjYjJG0oKUD2fATO0=,tag:utdbwvl9N4+bzrgIMmPnOg==,type:str]
kind: ENC[AES256_GCM,data:JKs7ZZRD,iv:fMT41X0jNe+ISrbvss2KkLgiDcqA30mkSowEjZEviEc=,tag:BjSwW3usJu9CY/mopCrqWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6Zid9rZSfc5bKkEkj16xuA==,iv:kgIfRP9fh1jA4P5ya4X8n31fLR7uhtNEPjgxmYuPnV4=,tag:f97cpIwm06WUK1ub/MVRcg==,type:str]
    namespace: ENC[AES256_GCM,data:lJxZofdZNU8jrFK8Nd4=,iv:w2JFjHATdfmaWG+NrkfpyINyFhTJWEvDffKGnef1Oxg=,tag:B8kNkjUau7Poo5kvvQ2beQ==,type:str]
type: ENC[AES256_GCM,data:ALSZpWlY,iv:mx4eZXacvi7V70tWKSWI1fgrWn5j2pxBj045dh8/pYA=,tag:92UgJ9B0ovME/D057j3CnQ==,type:str]
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:P1JYVvA7NijPvzS+2wW7TKLQpOg=,iv:rTrI5Jt2O8cM73pTv+LpXEXMuLBqcRCHK0MX37rpxto=,tag:xrMH9qF3KRLQAWs5IIBg8Q==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:5TqrZrLrqK+4swLyj2Sd7wG+r4F4GPv9yFc1sdEo0pbe6WbD848V2w==,iv:QoCscwfq5Pbu3IlANOsyTVS8s4JeIip0jSLhNPk3hNY=,tag:GYWgcMQEybYSU1Lu365hUw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:177696520379:alias/sops-key
          aws_profile: ""
          created_at: "2026-05-18T13:25:42Z"
          enc: AQICAHj4MZOP9L5gPEUID2GlYboKNeEEjG5MlVTqBJXW7DuCUAEbVeHwFJOZETVfX3xEYplsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9CLT+FkX7FgbVLMoAgEQgDsvqvScN45mdpC05KLmt7Af+YnAHEPY/jDHN+rLjmgVCFQUqGF/nRB/12nGKZJx1XmMgda3L2PvsMCzZQ==
    lastmodified: "2026-05-18T13:25:43Z"
    mac: ENC[AES256_GCM,data:+RCDjccOj3wEG8QTV4e5bkJgtbhoBARTy9lhi8FRZfULL4Y/NfgHyRikrK7pbq6g9ZlxPD2uyRtIn0fwUskbLkC1sezDxZzZfB60FQuy5WzR1uWsE+jUVDEBxYdDdRHxVwiYZiSZScfwrZ3xADMdU2R6h7cGs2Hr93hBdY4R2y4=,iv:RE3RZKxEcNiQvHGz0cNJHFXWXywIvAk3qXv7fIRTLQI=,tag:GS1lBt8ceZN/BfC+K0AsGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
